#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 17 20:48:46 2021

@author: amsterdam
"""
 
print("VÜCUT KİTLE ENDEKSİ HESAPLAMA PROGRAMI 💪")
boy = float(input("Boy (m):"))
kilo = int(input("Kilo (kg):"))
 
endeks  = kilo/(boy*boy)
 
if endeks <25:
    print("\n zayıf VKİ:{}".format(endeks))
elif endeks >= 25 and endeks <30:
    print("\n fazla kilolu VKİ:{}".format(endeks))
elif endeks >= 30 and endeks <40:
    print("\n obez VKİ:{}".format(endeks))
else:
    print("\n ciddi obez VKİ:{}".format(endeks))