#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 17 20:40:40 2021

@author: amsterdam
"""

vize = input('Vize Notunuz : ')
final = input('Final Notunuz : ')
ortalama=(float(vize)*0.4)+(float(final)*0.6)
print("Ortalama :{0} ".format(ortalama))
if(ortalama<50):
      print("Kaldınız")
else:
      print("Geçtiniz")